### ISSUE TITLE
[FR]: Release TODO

### ISSUE THREAD

**Issue by martinrotter** [martinrotter/rssguard#1036]
## 4.5.0
- [ ] Go through complete source code and fix documentation to include all major features description and fix existing.
- [ ] Finalize SQL layer for "Probes" feature

## 5.0.0
 - [ ] Rewrite article filtering objects to provide more clean approach - separate non-msg functions into proper separate object "reader" (for example list of available labels etc.)
 - [ ] Update docs with updated article filters features
